name: Playwright CI/CD

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install

    # Step 4: Install Playwright and Allure dependencies
    - name: Install Playwright and Allure
      run: |
        npm install playwright
        npm install -D allure-commandline

    # Step 5: Run tests with testpw (you can change this script name as per your package.json)
    - name: Run tests with testpw
      run: |
        npm run testpw

    # Step 6: Generate Allure report
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    # Step 7: Upload Allure report as a GitHub Artifact
    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report

